language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - composer install --no-interaction

notifications:
  on_success: never
  on_failure: always