#!/usr/bin/env php
<?php

require_once 'autoload.php';
require_once 'vendor/autoload.php';

$game = new Phong\Game(new Phong\State());

$screen = new Phong\CliScreen();

$game->setOutput($screen);
$game->setRefreshRate(24);

$game->start();

while ($game->isRunning()) {
    $game->poll();
}
