#!/usr/bin/env php
<?php

require_once 'autoload.php';

$game = new Phong\Game();

$screen = new Phong\CliScreen();

$game->setOutput($screen);
$game->setRefreshRate(10);

$game->start();

while ($game->isRunning()) {
    $game->poll();
}
